修复 当agp版本>=7.2.0 时 图片压缩任务失败的 bug
didi/booster pull request #366
Opened 2022-08-17 03:16 UTC by punkisnotdead3

当agp 版本>=7.2.0时，flat 文件中包含的path信息 为一种特殊的相对路径写法，导致从flat提取出来的路径 无法正确读取文件，
经过排查 当7.2.0 新增了一个任务 修改了flat文件中的path，这个任务会生成一个map文件 来标注 相对路径和绝对路径的关系，

所以只要读取这个文件 建立map关系，然后替换掉metadata中的 路径即可 解决该问题，否则 agp>7.2.0是 图片压缩成webp任务 会因为找不到文件而执行失败

2022-08-17 04:41 UTC, johnsonlee commented on booster-android-gradle-v7_2/src/main/kotlin/com/didiglobal/booster/android/gradle/v7_2/V72.kt
> +    override val BaseVariant.mapSourceSetTaskProvider: TaskProvider<out Task>
属性名跟 task name 保持一致

2022-08-17 08:40 UTC, punkisnotdead3 commented
已梳理逻辑重新提交，新增了一个metadata的扩展方法 仅用于 agp7.2

2022-08-17 11:39 UTC, johnsonlee commented
* 没必要修改 `booster-aapt2`
* 没必要对大部分版本都不兼容的 API 做实现

2022-08-17 14:47 UTC, punkisnotdead3 commented
> * 没必要修改 `booster-aapt2`

这里有点疑惑，如果metadata的sourcePath不能修改为var的话，那么metadata在构建的时候 就要传 绝对路径进去，但是metadata构建的地方就在aapt2Parser中，这里还有啥别的好一点的修改方法？

2022-08-17 14:49 UTC, punkisnotdead3 commented
> * 没必要对大部分版本都不兼容的 API 做实现

这个是指v33 v41 等实现中 那些 todo吗? 如果是这样的话，就把对应的task和产物路径 扩展属性 从base中取出来 在用的时候直接取就行了吧？

2022-08-20 02:24 UTC, johnsonlee commented
> 

Bingo

2022-08-21 08:58 UTC, punkisnotdead3 commented
1.新增了png质量压缩 对agp720的适配
2.去除了basevarint中 mapSourceSetPath的task 实现

todo：
1.暂未找到  同时满足 不修改metadata 中path val 变更为var 且 不修改aapt2Parser 实现的情况下 可以修改sourcePath
2. 暂未找到 可以去掉 BaseVariant.sourceSetMap 实现的方法，主要是 InternalArtifactType.SOURCE_SET_PATH_MAP 这个属性只有agp7.2.0 中才有，如果去掉这个实现 那么在task 中 因为task 依赖的gradle api 不是7.2.0 所以 找不到这个依赖

2022-08-21 12:11 UTC, johnsonlee commented
> 1.新增了png质量压缩 对agp720的适配 2.去除了basevarint中 mapSourceSetPath的task 实现
> 
> todo： 1.暂未找到 同时满足 不修改metadata 中path val 变更为var 且 不修改aapt2Parser 实现的情况下 可以修改sourcePath 2. 暂未找到 可以去掉 BaseVariant.sourceSetMap 实现的方法，主要是 InternalArtifactType.SOURCE_SET_PATH_MAP 这个属性只有agp7.2.0 中才有，如果去掉这个实现 那么在task 中 因为task 依赖的gradle api 不是7.2.0 所以 找不到这个依赖

可以使用 `AGPInterface` 中提供的 [val BaseVariant.allArtifacts: Map<String, FileCollection>](https://reference.johnsonlee.io/booster/com.didiglobal.booster.gradle/-a-g-p-interface/all-artifacts.html) API

2022-08-21 14:24 UTC, punkisnotdead3 commented
> > 1.新增了png质量压缩 对agp720的适配 2.去除了basevarint中 mapSourceSetPath的task 实现
> > todo： 1.暂未找到 同时满足 不修改metadata 中path val 变更为var 且 不修改aapt2Parser 实现的情况下 可以修改sourcePath 2. 暂未找到 可以去掉 BaseVariant.sourceSetMap 实现的方法，主要是 InternalArtifactType.SOURCE_SET_PATH_MAP 这个属性只有agp7.2.0 中才有，如果去掉这个实现 那么在task 中 因为task 依赖的gradle api 不是7.2.0 所以 找不到这个依赖
> 
> 可以使用 `AGPInterface` 中提供的 [val BaseVariant.allArtifacts: Map<String, FileCollection>](https://reference.johnsonlee.io/booster/com.didiglobal.booster.gradle/-a-g-p-interface/all-artifacts.html) API

感谢，已用 variant.allArtifacts["SOURCE_SET_PATH_MAP"] 替换实现

2022-08-22 12:55 UTC, johnsonlee commented on booster-aapt2/src/main/kotlin/com/didiglobal/booster/aapt2/Aapt2Parser.kt
> +    BinaryParser(this).use { parser ->
不要修改 `Aapt2Parser`

2022-08-22 12:57 UTC, johnsonlee commented on booster-task-compression/src/main/kotlin/com/didiglobal/booster/compression/task/CompressImages.kt
> +
可以考虑用 `lazy` 代替单独的方法

2022-08-22 12:57 UTC, johnsonlee requested changes
请删掉用于调试的 `println`

2022-08-22 16:11 UTC, punkisnotdead3 commented on booster-task-compression/src/main/kotlin/com/didiglobal/booster/compression/task/CompressImages.kt
> +
This annotation is not applicable to target 'member property with delegate'

普通变量 可以用by lazy ，但是task中 必须要用 @Internal 注解 来标识这个变量 ， by lazy就会报错 似乎不能用这个

2022-08-22 17:10 UTC, punkisnotdead3 commented
更新：
1、 去除调试信息
2、 去除AAPT parser 的修改，改用METAData的扩展方法 来实现 路径替换
3、by lazy 暂时无法在 internal 注解的变量上使用，故暂时保留initSourceMap方法

2022-08-22 20:21 UTC, johnsonlee commented on booster-task-compression-cwebp/src/main/kotlin/com/didiglobal/booster/task/compression/cwebp/CwebpCompressFlatImages.kt
> +        initSourceSetMap()
为什么不在父类中统一初始化？

2022-08-22 20:25 UTC, johnsonlee commented on booster-task-compression/src/main/kotlin/com/didiglobal/booster/compression/task/CompressImages.kt
> +
`Metadata.sourcePath` => `Metadata.getSourceAbsolutePath()` 影响面太大

2022-08-22 20:30 UTC, johnsonlee commented on booster-task-compression-cwebp/src/main/kotlin/com/didiglobal/booster/task/compression/cwebp/CwebpCompressFlatImages.kt
>              it to it.metadata
在这里重新构造一个新的 `Metadata` 不好吗？

例如：

```kotlin
it.metadata.remap()
```

```kotlin
fun Metadata.remap(): Metadata {
    return sourceSetPaths[sourcePath]?.let { origin ->
        copy(sourcePath = origin)
    } ?: this
}
```

2022-08-23 02:18 UTC, punkisnotdead3 commented on booster-task-compression-cwebp/src/main/kotlin/com/didiglobal/booster/task/compression/cwebp/CwebpCompressFlatImages.kt
>              it to it.metadata
已修复

2022-08-23 02:19 UTC, punkisnotdead3 commented on booster-task-compression-cwebp/src/main/kotlin/com/didiglobal/booster/task/compression/cwebp/CwebpCompressFlatImages.kt
> +        initSourceSetMap()
已在对应的abs类中初始化，CompressImages 中没有流程调用的函数，故不在此类中初始化，分别在 AbstractPngquantCompressImages  AbstractCwebpCompressImages 进行初始化

2022-08-23 04:43 UTC, johnsonlee requested changes

2022-08-23 04:43 UTC, johnsonlee commented on booster-task-compression/src/main/kotlin/com/didiglobal/booster/compression/task/CompressImages.kt
> +    val sourceSetMap = hashMapOf<String, String>()
请声明为 immutable 的 map

```kotlin
val sourceSetPaths: Map<String, String> by lazy(::initSourceSetPaths)
```

2022-08-23 04:43 UTC, johnsonlee commented on booster-task-compression/src/main/kotlin/com/didiglobal/booster/compression/task/CompressImages.kt
> +        }
还可以更 Kotlin 一点

2022-08-23 04:43 UTC, johnsonlee commented on booster-task-compression/src/main/kotlin/com/didiglobal/booster/compression/task/CompressImages.kt
> +        return this
还可以更 Kotlin 一点

2022-08-23 04:50 UTC, johnsonlee commented on booster-task-compression/src/main/kotlin/com/didiglobal/booster/compression/task/CompressImages.kt
> +
```kotlin
    @get:Internal
    val sourceSetPaths: Map<String, String> by lazy {
        initSourceSetPaths()
    }

    private fun initSourceSetPaths(): Map<String, String> {
        return mapOf()
    }
```

2022-08-23 09:19 UTC, punkisnotdead3 commented on booster-task-compression/src/main/kotlin/com/didiglobal/booster/compression/task/CompressImages.kt
> +        return this
已修改

2022-08-23 09:21 UTC, punkisnotdead3 commented on booster-task-compression/src/main/kotlin/com/didiglobal/booster/compression/task/CompressImages.kt
> +    val sourceSetMap = hashMapOf<String, String>()
这里有点疑惑 还暂未修改

主要是 @Internal 这个注解 的变量 没办法用by lazy，用了就提示错误， 不用 @Internal 这个变量 编译能过 运行时gradle 会报错

这就尬住了， 不用by lazy 的情况下，我如果定义这个immutable的 map 那么后面我没办法往这个map put key-value 进去   求解

2022-08-23 12:07 UTC, punkisnotdead3 commented
想了想， 既然  @Internal 和 by lazy 有冲突的情况下， 用lateinit var  来定义一个immutable map 不知道是否可行？

但这样val 就变成了var 似乎也没有完全解决问题

2022-08-23 12:54 UTC, johnsonlee commented on booster-task-compression/src/main/kotlin/com/didiglobal/booster/compression/task/CompressImages.kt
> +    val sourceSetMap = hashMapOf<String, String>()
```kotlin
@get:Internal
```

2022-08-23 13:19 UTC, johnsonlee requested changes

2022-08-23 13:19 UTC, johnsonlee commented on booster-task-compression/src/main/kotlin/com/didiglobal/booster/compression/task/CompressImages.kt
> +                sourceSetMap[it[0].substringBeforeLast("-")] = it[1]
为什么要截取最后的 `-` 前面的子串？直接用不行吗？

2022-08-23 13:19 UTC, johnsonlee commented on booster-task-compression/src/main/kotlin/com/didiglobal/booster/compression/task/CompressImages.kt
> +        val array = sourcePath.split(":")
应该先判断 AGP 版本再决定要不要解析

2022-08-23 13:19 UTC, johnsonlee commented on booster-task-compression/src/main/kotlin/com/didiglobal/booster/compression/task/CompressImages.kt
> +            sourcePath = "${sourceSetMap[array[0].substringBeforeLast("-")]}${array[1]}"
截子串多此一举

2022-08-23 13:33 UTC, punkisnotdead3 commented on booster-task-compression/src/main/kotlin/com/didiglobal/booster/compression/task/CompressImages.kt
> +                sourceSetMap[it[0].substringBeforeLast("-")] = it[1]
有些flat文件解析出来，他的相对路径信息 是
com.xxx.yyy.app-main-111 开头的
然而这个 开头的信息 在sourceSetPathMap路径文件中 并找不到，能找到的 只有 com.xxx.yyy.app-main-110
有时候会变成com.xxx.yyy.app-main-109

目前还没搞清楚-yyy 后面这个yyy的具体含义，如果不去除这个yyy的话 会导致某些路径匹配不上 造成部分图片
转webp失败， 我这边反复测试了下 只有-yyy 这个信息 才能保证全部匹配上。

2022-08-23 13:44 UTC, johnsonlee commented on booster-task-compression/src/main/kotlin/com/didiglobal/booster/compression/task/CompressImages.kt
> +                sourceSetMap[it[0].substringBeforeLast("-")] = it[1]
最后的数字只是一个自增序号

2022-08-23 14:19 UTC, johnsonlee commented on booster-task-compression/src/main/kotlin/com/didiglobal/booster/compression/task/CompressImages.kt
> +                sourceSetMap[it[0].substringBeforeLast("-")] = it[1]
AGP 7.2.1+ 有 bug

2022-08-23 14:57 UTC, punkisnotdead3 commented on booster-task-compression/src/main/kotlin/com/didiglobal/booster/compression/task/CompressImages.kt
> +                sourceSetMap[it[0].substringBeforeLast("-")] = it[1]
但是现在不截掉最后 -yyy 这个序号 始终会漏掉 一部分图片，所以没办法我只能截取的吧？

2022-08-23 15:16 UTC, johnsonlee commented on booster-task-compression/src/main/kotlin/com/didiglobal/booster/compression/task/CompressImages.kt
> +            }
直接用 `associate` 不香么？

2022-08-23 15:18 UTC, johnsonlee commented on booster-task-compression/src/main/kotlin/com/didiglobal/booster/compression/task/CompressImages.kt
> +                map[it[0].substringBeforeLast("-")] = it[1]
截断可能会导致出现重复的 `key`

2022-08-23 15:37 UTC, punkisnotdead3 commented on booster-task-compression/src/main/kotlin/com/didiglobal/booster/compression/task/CompressImages.kt
> +                map[it[0].substringBeforeLast("-")] = it[1]
> 

有道理 我改下

2022-08-23 16:06 UTC, punkisnotdead3 commented on booster-task-compression/src/main/kotlin/com/didiglobal/booster/compression/task/CompressImages.kt
> +            }
> 直接用 `associate` 不香么？

已修复该问题

2022-08-23 16:15 UTC, johnsonlee commented on booster-task-compression/src/main/kotlin/com/didiglobal/booster/compression/task/CompressImages.kt
> +            }?.filter { it.size >= 2 }?.associateBy(keySelector = { it[0] }, valueTransform = { it[1] }) ?: emptyMap()
直接 `associate` 就行了，干嘛要用 `associateBy` ?

2022-08-23 16:20 UTC, johnsonlee commented on booster-task-compression/src/main/kotlin/com/didiglobal/booster/compression/task/CompressImages.kt
> +            }?.filter { it.size >= 2 }?.associateBy(keySelector = { it[0] }, valueTransform = { it[1] }) ?: emptyMap()
```kotlin
?.associate { (key, value) ->
    key to value
}
```

2022-11-05 11:09 UTC, closed without merging